name: "Synchronisation des Labels sur Tous les Repos"

on:
  schedule:
    - cron: "0 0 * * 1"  # Exécute chaque lundi à minuit
  workflow_dispatch:

jobs:
  sync-labels:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v2

      - name: 📂 Vérifier la présence du fichier labels.json
        run: |
          if [ ! -f .github/config/labels.json ]; then
            echo "❌ labels.json n'existe pas !"
            exit 1
          else
            echo "✅ labels.json trouvé !"
          fi

      - name: 🔍 Vérifier si le token accède aux repositories
        env:
          GH_TOKEN: ${{ secrets.LABELGITHUB_TOKEN }}
        run: |
          echo "🔍 Récupération de la liste des repositories..."
          gh api user/repos --paginate --jq '.[].full_name' > repos_list.txt

          if [ ! -s repos_list.txt ]; then
            echo "❌ Aucun repository trouvé !"
            exit 1
          fi

          cat repos_list.txt

      - name: ⚡ Ne supprimer que les labels obsolètes et ajouter les nouveaux
        env:
          GH_TOKEN: ${{ secrets.LABELGITHUB_TOKEN }}
        run: |
          echo "🔍 Début du traitement des repositories..."

          while IFS= read -r repo; do
            if [[ "$repo" == "djoudj-dev/.gitworkflow" ]]; then
              echo "⚠️ Ignoré : $repo (repository privé)"
              continue
            fi

            echo "📌 Vérification du repository $repo"

            if gh api repos/"$repo" --silent; then
              echo "✅ Récupération des labels actuels de $repo..."
              
              # Obtenir la liste des labels existants
              EXISTING_LABELS=$(gh api repos/"$repo"/labels --jq '.[].name' | tr -d '"')

              # Obtenir la liste des labels définis dans labels.json
              NEW_LABELS=$(jq -r '.[].name' .github/config/labels.json)

              # Trouver les labels à supprimer (ceux qui existent mais ne sont pas définis dans labels.json)
              LABELS_TO_DELETE=$(comm -23 <(echo "$EXISTING_LABELS" | sort) <(echo "$NEW_LABELS" | sort))

              # Supprimer les labels obsolètes un par un
              echo "$LABELS_TO_DELETE" | while IFS= read -r label; do
                if [ -n "$label" ]; then
                  echo "🗑️ Suppression du label : $label"
                  gh api -X DELETE repos/"$repo"/labels/"$label" || echo "⚠️ Impossible de supprimer $label"
                fi
              done

              echo "✅ Ajout des nouveaux labels pour $repo"

              # Ajouter les nouveaux labels un par un
              jq -c '.[]' .github/config/labels.json | while IFS= read -r label; do
                NAME=$(echo "$label" | jq -r ".name")
                DESCRIPTION=$(echo "$label" | jq -r ".description")
                COLOR=$(echo "$label" | jq -r ".color")

                echo "📌 Ajout du label : $NAME"

                gh api -X POST repos/"$repo"/labels \
                  -H "Accept: application/vnd.github.v3+json" \
                  -f name="$NAME" \
                  -f description="$DESCRIPTION" \
                  -f color="$COLOR" || echo "⚠️ Impossible d'ajouter $NAME"
              done

            else
              echo "⚠️ Le repo $repo est inaccessible. Il sera ignoré."
            fi
          done < repos_list.txt
