name: "Synchronisation des Labels sur Tous les Repos"

on:
  schedule:
    - cron: "0 0 * * 1"  # Exécute chaque lundi à minuit
  workflow_dispatch:

jobs:
  sync-labels:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v2

      - name: 📂 Vérifier la présence du fichier labels.yml
        run: |
          if [ ! -f .github/config/labels.yml ]; then
            echo "❌ labels.yml n'existe pas !"
            exit 1
          else
            echo "✅ labels.yml trouvé !"
          fi

      - name: 🔍 Vérifier si le token accède aux repositories
        env:
          GH_TOKEN: ${{ secrets.LABELGITHUB_TOKEN }}
        run: |
          echo "🔍 Récupération de la liste des repositories..."
          gh api user/repos --paginate --jq '.[].full_name' > repos_list.txt
          cat repos_list.txt || echo "❌ Erreur : Impossible de récupérer les repositories"

      - name: Lister tous les repos et appliquer les labels
        env:
          GH_TOKEN: ${{ secrets.LABELGITHUB_TOKEN }}
        run: |
          echo "🔍 Début du traitement des repositories..."

          # Lire les repositories récupérés
          while read -r repo; do
            # Ignorer le repo privé `.gitworkflow`
            if [[ "$repo" == "djoudj-dev/.gitworkflow" ]]; then
              echo "⚠️ Ignoré : $repo (repository privé)"
              continue
            fi

            echo "📌 Vérification du repository $repo"

            # Vérifier si le repo est accessible avant d'envoyer la requête
            if gh api repos/$repo --silent; then
              echo "✅ Mise à jour des labels pour $repo"
              gh api -X POST repos/$repo/labels \
                -H "Accept: application/vnd.github.v3+json" \
                --input .github/config/labels.yml
            else
              echo "⚠️ Le repo $repo est inaccessible. Il sera ignoré."
            fi
          done < repos_list.txt
