name: "Synchronisation des Labels sur Tous les Repos"

on:
  schedule:
    - cron: "0 0 * * 1"  # Exécute chaque lundi à minuit
  workflow_dispatch:

jobs:
  sync-labels:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v2

      - name: 📂 Vérifier la présence du fichier labels.json
        run: |
          if [ ! -f .github/config/labels.json ]; then
            echo "❌ labels.json n'existe pas !"
            exit 1
          else
            echo "✅ labels.json trouvé !"
          fi

      - name: 🔍 Vérifier si le token accède aux repositories
        env:
          GH_TOKEN: ${{ secrets.LABELGITHUB_TOKEN }}
        run: |
          echo "🔍 Récupération de la liste des repositories..."
          gh api user/repos --paginate --jq '.[].full_name' > repos_list.txt

          if [ ! -s repos_list.txt ]; then
            echo "❌ Aucun repository trouvé !"
            exit 1
          fi

          cat repos_list.txt

      - name: Lister tous les repos et appliquer les labels
        env:
          GH_TOKEN: ${{ secrets.LABELGITHUB_TOKEN }}
        run: |
          echo "🔍 Début du traitement des repositories..."

          while read -r repo; do
            # Ignorer le repo privé `.gitworkflow`
            if [[ "$repo" == "djoudj-dev/.gitworkflow" ]]; then
              echo "⚠️ Ignoré : $repo (repository privé)"
              continue
            fi

            echo "📌 Vérification du repository $repo"

            # Vérifier si le repo est accessible avant d'envoyer la requête
            if gh api repos/$repo --silent; then
              echo "✅ Suppression des anciens labels pour $repo"

              # Récupérer et supprimer tous les labels existants
              gh api repos/$repo/labels --jq '.[].name' | tr -d '"' | while read -r label; do
                echo "🗑️ Suppression du label : $label"
                gh api -X DELETE repos/$repo/labels/"$label" || echo "⚠️ Impossible de supprimer $label"
                sleep 1  # Pause pour éviter de dépasser la limite API GitHub
              done

              echo "✅ Ajout des nouveaux labels pour $repo"

              # Lire et ajouter les labels un par un depuis le fichier JSON
              jq -c '.[]' .github/config/labels.json | while read -r label; do
                NAME=$(echo "$label" | jq -r '.name')
                DESCRIPTION=$(echo "$label" | jq -r '.description')
                COLOR=$(echo "$label" | jq -r '.color')

                echo "📌 Ajout du label : $NAME"

                gh api -X POST repos/$repo/labels \
                  -H "Accept: application/vnd.github.v3+json" \
                  -f name="$NAME" \
                  -f description="$DESCRIPTION" \
                  -f color="$COLOR" || echo "⚠️ Impossible d'ajouter $NAME"

                sleep 1  # Pause pour éviter de dépasser la limite API GitHub
              done
            else
              echo "⚠️ Le repo $repo est inaccessible. Il sera ignoré."
            fi
          done < repos_list.txt
