name: "Synchronisation des Labels sur Tous les Repos"

on:
  schedule:
    - cron: "0 0 * * 1"  # Exécute chaque lundi à minuit
  workflow_dispatch:

jobs:
  sync-labels:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v2

      - name: Lister tous les repos de l'utilisateur et appliquer les labels
        env:
          GH_TOKEN: ${{ secrets.LABELGITHUB_TOKEN }}
        run: |
          echo "🔍 Récupération de la liste des repositories..."
          
          # Récupérer tous les repositories de l'utilisateur
          REPOS=$(gh api user/repos --paginate --jq '.[].full_name')

          # Appliquer les labels sur chaque repository
          for repo in $REPOS; do
            echo "📌 Mise à jour des labels pour $repo"
            gh api repos/$repo/labels \
              --method PUT \
              --input .github/config/labels.json \
              --auth $LABELGITHUB_TOKEN
          done
