name: "Synchronisation des Labels sur Tous les Repos"

on:
  schedule:
    - cron: "0 0 * * 1"  # Exécute chaque lundi à minuit
  workflow_dispatch:

jobs:
  sync-labels:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v2

      - name: Lister tous les repos et appliquer les labels
        env:
          GH_TOKEN: ${{ secrets.LABELGITHUB_TOKEN }}
        run: |
          echo "🔍 Récupération de la liste des repositories..."
          
          # Récupérer tous les repositories de l'utilisateur
          REPOS=$(gh api user/repos --paginate --jq '.[].full_name')

          # Vérifier si la liste des repos est vide
          if [ -z "$REPOS" ]; then
            echo "❌ Aucun repository trouvé !"
            exit 1
          fi

          # Appliquer les labels sur chaque repository
          echo "$REPOS" | while read -r repo; do
            echo "📌 Mise à jour des labels pour $repo"
            gh api repos/$repo/labels \
              --method PUT \
              --input .github/config/labels.json
          done
